name: be_my_hear
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5
  video_player: ^2.3.0
  firebase_core: ^1.14.1
  firebase_storage: ^10.2.12
  firebase_auth: ^3.3.18
  speech_to_text: ^5.5.0
  avatar_glow: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - bg.png

avatar_glow:
  git:
    url: https://github.com/apgapg/avatar_glow
    ref: master